const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const reviewSchema = new Schema({
  user: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  rating: { type: Number, required: true, min: 1, max: 5 },
  comment: { type: String, default: '' },
}, { timestamps: true });

const variantSchema = new Schema({
  colorName: String,
  hexCode: String,
  sizes: [String],          // Sizes as an array
  prices: [Number],         // Prices as an array
  stock: Number,            // Legacy field - keeping for backward compatibility
  stockBySize: [Number],    // Stock for each size in the sizes array
  description: String,
  discountPrices: [Number], // Discount prices as an array
  badgeNames: [String],     // Badge names as an array
  badgeColors: [String],    // Badge colors as an array
  images: [String],
  measureType: { type: String, required: true },
  unitName: { type: String, required: true },
  specifications: [{
    name: String,
    value: String,
    unit: String
  }],
 
  shippingOptions: [{
    name: String,
    charge: Number,
    estimatedDays: Number,
  }],
  // References to the Shipping docs the options were built from (needed to
  // restore selections when editing the product later)
  shippingIds: [{ type: Schema.Types.ObjectId, ref: 'Shipping' }],
  // AI-generated SEO metadata for this specific variant
  seo: {
    metaTitle: { type: String, default: '' },
    metaDescription: { type: String, default: '' },
    metaKeywords: { type: String, default: '' },
    ogImage: { type: String, default: '' },
    autoGenerated: { type: Boolean, default: false },
    lastGenerated: { type: Date },
  }
}, { timestamps: true });

const productSchema = new Schema({
  name: { type: String, required: true, unique: true },
  sku: { type: String, trim: true, index: true, unique: true, sparse: true },
  categories: [String],
  brand: { type: String },
  broadcast: { type: Boolean, default: false },
  likesCount: { type: Number, default: 0 },
  mainPrice: Number,
  discountPrice: Number,
  mainBadgeName: String,
  mainBadgeColor: String,
  gender: { type: String, enum: ['Male', 'Female', 'Unisex'], required: true },
  measureType: { type: String, required: true },
  unitName: { type: String, required: true },
  variants: [variantSchema],
  mainImage: { type: String, required: true },
  // Reviews
  reviews: [reviewSchema],
  averageRating: { type: Number, default: 0 },
  totalReviews: { type: Number, default: 0 },
  // Vector embedding for semantic search
  embedding: { type: [Number], default: undefined },
  // AI-generated SEO metadata
  seo: {
    metaTitle: { type: String, default: '' },
    metaDescription: { type: String, default: '' },
    metaKeywords: { type: String, default: '' },
    ogImage: { type: String, default: '' },
    autoGenerated: { type: Boolean, default: false },
    lastGenerated: { type: Date },
  }
}, { timestamps: true });

module.exports = mongoose.model('Product', productSchema);
