const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const { sanitizeRichHtml } = require('../utils/sanitizeHtml');

const reviewSchema = new Schema({
  user: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  rating: { type: Number, required: true, min: 1, max: 5 },
  comment: { type: String, default: '' },
}, { timestamps: true });

const variantSchema = new Schema({
  // Region + options are the canonical configuration path. The legacy parallel
  // arrays below remain readable while existing catalog records are migrated.
  regionId: { type: Schema.Types.ObjectId, ref: 'Region', default: null },
  colorName: String,
  hexCode: String,
  options: [{
    size: { type: String, default: '' },
    measureType: { type: String, default: '' },
    unitName: { type: String, default: '' },
    price: { type: Number, min: 0 },
    discountPrice: { type: Number, min: 0 },
    costPrice: { type: Number, min: 0 },
    stock: { type: Number, min: 0, default: 0 },
    badgeName: { type: String, default: '' },
    badgeColor: { type: String, default: '' },
  }],
  sizes: [String],          // Sizes as an array
  prices: [Number],         // Prices as an array
  costPrice: { type: Number, min: 0 },
  stock: Number,            // Legacy field - keeping for backward compatibility
  stockBySize: [Number],    // Stock for each size in the sizes array
  description: String,
  discountPrices: [Number], // Discount prices as an array
  badgeNames: [String],     // Badge names as an array
  badgeColors: [String],    // Badge colors as an array
  images: [String],
  measureType: { type: String, required: true },
  unitName: { type: String, required: true },
  specifications: [{
    name: String,
    value: String,
    unit: String
  }],
 
  shippingOptions: [{
    name: String,
    charge: Number,
    estimatedDays: Number,
  }],
  // References to the Shipping docs the options were built from (needed to
  // restore selections when editing the product later)
  shippingIds: [{ type: Schema.Types.ObjectId, ref: 'Shipping' }],
  // Generated or admin-edited SEO metadata for this specific variant
  seo: {
    metaTitle: { type: String, default: '' },
    metaDescription: { type: String, default: '' },
    metaKeywords: { type: String, default: '' },
    ogImage: { type: String, default: '' },
    autoGenerated: { type: Boolean, default: false },
    lastGenerated: { type: Date },
  }
}, { timestamps: true });

const productSchema = new Schema({
  name: { type: String, required: true, unique: true },
  sku: { type: String, trim: true, index: true, unique: true, sparse: true },
  categories: [String],
  brand: { type: String },
  regionId: { type: Schema.Types.ObjectId, ref: 'Region', default: null },
  regions: [{ type: Schema.Types.ObjectId, ref: 'Region' }],
  broadcast: { type: Boolean, default: false },
  // Product-wide setting: every configured variant requires online wallet payment.
  isDigitalProduct: { type: Boolean, default: false },
  isPreOrder: { type: Boolean, default: false },
  preOrderEstimatedDate: { type: Date, default: null },
  comingSoon: { type: Boolean, default: false },
  likesCount: { type: Number, default: 0 },
  // Keep individual product likes private while allowing atomic state changes.
  likedBy: { type: [Schema.Types.ObjectId], default: [], select: false },
  mainPrice: Number,
  discountPrice: Number,
  costPrice: { type: Number, min: 0 },
  mainBadgeName: String,
  mainBadgeColor: String,
  // Gender choices are managed from the admin catalog (for example: Both,
  // Unisex, or store-specific audience labels), so don't constrain them to a
  // stale hardcoded enum here.
  gender: { type: String, trim: true, required: true },
  measureType: { type: String, required: true },
  unitName: { type: String, required: true },
  variants: [variantSchema],
  mainImage: { type: String, required: true },
  // Reviews
  reviews: [reviewSchema],
  averageRating: { type: Number, default: 0 },
  totalReviews: { type: Number, default: 0 },
  // Generated or admin-edited SEO metadata
  seo: {
    metaTitle: { type: String, default: '' },
    metaDescription: { type: String, default: '' },
    metaKeywords: { type: String, default: '' },
    ogImage: { type: String, default: '' },
    autoGenerated: { type: Boolean, default: false },
    lastGenerated: { type: Date },
  }
}, {
  timestamps: true,
  toJSON: {
    transform(_doc, ret) {
      for (const variant of ret.variants || []) {
        variant.description = sanitizeRichHtml(variant.description || '');
      }
      return ret;
    },
  },
});

productSchema.pre('validate', function sanitizeProductDescriptions(next) {
  for (const variant of this.variants || []) {
    variant.description = sanitizeRichHtml(variant.description || '');
  }
  next();
});

productSchema.index({ createdAt: -1, _id: -1 });

module.exports = mongoose.model('Product', productSchema);
