const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const staticPageSchema = new Schema({
  slug: { type: String, required: true, unique: true, lowercase: true, trim: true, index: true },
  title: { type: String, required: true, trim: true },
  seo: {
    metaTitle: { type: String, default: '' },
    metaDescription: { type: String, default: '' },
    metaKeywords: { type: String, default: '' },
    ogImage: { type: String, default: '' },
    autoGenerated: { type: Boolean, default: false },
    lastGenerated: { type: Date },
  },
}, { timestamps: true });

module.exports = mongoose.model('StaticPage', staticPageSchema, 'static-pages');
